on:
  push:
    branches:
      - main

name: Render


# permissions: 
#     contents: write
#     pages: write

jobs:
  render:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 

      - name: Setup Python
        uses: actions/setup-python@v3

      - name: Render project
        run: quarto render


